### ISSUE TITLE
Hanging

### ISSUE THREAD

**Issue by cnguy** [Colorfulstan/RiotRateLimiter-node#7]
I haven't read all the code, but I was wondering why it "hangs" and if it's intended or not.

This is only really important when trying to pass my lib through Travis CI (which also runs a code coverage tool).

https://travis-ci.org/cnguy/kayn/builds/290500366#L552

I set up a single test for now, which quickly executes. Then, the tests are done, but something is running in the background.

Thanks in advance!

Edit: this is only needed if I want to fully test the actual response
But now that I think about it, I could just mock requests as a start if I simply just want to test my API

**Comment by Colorfulstan** [comment]
I don't have experience with Travis, so I can't really tell what might cause it.

In terms of background activitiy, I assume that the Rate-limits keep executing their timeouts for limit resets. Do you think this is a general issue, or just a quirk with Travis?

Having looked up the issue on google it might help if you allow travis to [run with sudo](https://github.com/travis-ci/travis-ci/issues/6861#issuecomment-262277891), so it can kill the process after the build is done. 

 happening with multiple setups that require specific shutdown of the process see for example https://github.com/travis-ci/travis-ci/issues/6861#issuecomment-262277891
and related issues.

**Comment by cnguy** [comment]
It's not specifically a Travis CI issue, the limiter can be isolated to some random script and it'll hang (through the timeouts).

I'm already running sudo: true, and the multiple setups = they're usually running extra stuffs like Selenium and whatnot. Still gonna try a bunch of things to see if this is actually an issue or not, I'll get back to you whenever.

**Comment by Colorfulstan** [comment]
I can't think of how to write a test for this, but I proxy tested it.
In my LeagueJS library, the test-suites would show the hanging behavior, not exiting after execution.
The change fixes that, so It seems to be working as intended now.
