### ISSUE TITLE
Method-Rate-Limits exceeded

### ISSUE THREAD

**Issue by TheCraccer** [Colorfulstan/RiotRateLimiter-node#9]
We got some 429er errors in our project. First, we had about 16 429-responses where the `x-rate-limit-type` was not present. But after that errors kept occurring with increasing rate. This time the `x-rate-limit-type` was `method`.

For clarification: We are using a cronjob which analyses our users and their recent games. I attached the logged errors to this issue.
[20171121_429-error.log](https://github.com/Colorfulstan/RiotRateLimiter-node/files/1491942/20171121_429-error.log)

**Comment by Colorfulstan** [comment]
So if you're using a cronjob, are you creating a new instance of LeagueJS within the script, that the cronjob executes?

**Comment by TheCraccer** [comment]
No we are using the same instance of LeagueJS and the RiotRateLimiter every time. Maybe it's part of the edge case, where the RateLimiter reset the limits, but Riot did not yet?

**Comment by Colorfulstan** [comment]
Is it a consistent issue, or like a one time thing?

**Comment by Colorfulstan** [comment]
I assume you run the analysis for multiple users in parallel?

**Comment by TheCraccer** [comment]
1. Everything works pretty fine for about 2-3 hours and then the errors are occuring with increasing rate. It's not like its coming every time then tho.

2. Yepp we do run multiple analysis at once. The 429-errors only occur for getting matches (method-limit). The rate of 429-errors is at about 1-2%. They come totally randomly, 100 at once, then no errors for an hour and so on...

**Comment by Colorfulstan** [comment]
Ok so I think you're right with it being a sync Issue between the Limiter and Riot then.
> Maybe it's part of the edge case, where the RateLimiter reset the limits, but Riot did not yet?

As of how the sync works when using SPREAD is: 

* with every response, the interval for the next request is calculated based on the rate limit information

So even though using SPREAD should minimize sync issues, if you're running a lot of parallel calls there still might be race conditions happening. Most likely some intervals are updated with outdated rate limit information, which then propagates through all analysis tasks that are using that Rate-Limit (Match for the specific region).

**Comment by Colorfulstan** [comment]
Looks like the updating for the limits is broken in general...will try to fix this asap

**Comment by Colorfulstan** [comment]
@TheCraccer I reverted the commit that introduced a limit-update bug.
Please update LeagueJS (1.6.0) and let me know if you encounter this issue again.
